### PR TITLE
Add: Global Composer Dependencies to README

### PR DESCRIPTION
**Pull request by ctsstc**
Adds documentation about how to handle global composer dependencies.

Not certain if you need to reshim after you change php versions?

See #54 and #55

### CODE REVIEW

**Review by smorimoto — APPROVED** [review]

**Comment by smorimoto** [comment]
Looks good. Thanks @ctsstc.

@vic By the way, is there a smartest solution to avoid this? I think `asdf-golang` needed a similar process; it's certainly not very smart.

**Comment by vic** [comment]
as far as I can remember, there's no other way around installing new package binaries than regenerating via reshim (that is without using something like direnv).

plugins can having a `bin/bin_paths` (can't remember if that's the actual hook name ) can provide a list of directories containing executables, but again that's for asdf to be able to generate shims for them.

there's a plug-in file `bin/env` (again can't remember the name right now) where you can export environment variables but they are intended to setup a correct environment immediately before shims execution (eg GOPATH).

**Comment by smorimoto** [comment]
It might be best to recommend adding some paths to the user at README, but that conflicts with the previous PR, so I will merge this PR for now.

**Comment by smorimoto** [comment]
Thanks again @ctsstc.

**Pull request merged**
