### PR TITLE
Allow running Composer's global binaries

### LINKED ISSUE #54: Add Global Composer Binaries to PATH
Add the `vendor/bin` directory of `$COMPOSER_HOME` or `~/.config/composer/vendor/bin` to PATH. This will allow running globally installed Composer packages.

### PR DESCRIPTION
**Pull request by RobLoach**
This sets up the composer home directory so that you can run vendor binaries. For example...

``` bash
composer global require friendsofphp/php-cs-fixer
asdf reshim
php-cs-fixer --version
```

Fixes #54

### CODE REVIEW

**Comment by imbsky** [comment]
I will check this.

**Comment by RobLoach** [comment]
Thanks! Been using it for the past few days to use global binaries. Been working pretty well.

One thing I've found is the need to `asdf reshim` after installing new binaries, which makes sense.

**Comment by imbsky** [comment]
Thanks @RobLoach!

**Comment by RobLoach** [comment]
No, thank you! :dancing_men:

**Comment by imbsky** [comment]
@all-contributors please add @RobLoach for code

**Comment by ctsstc** [comment]
We should get this into the documentation. I had to dig through issues to see if someone handled composer globals and stumbled across this after digging around. Nice job fixing this up :)

**Pull request merged**
